const latinNames = [
    "Gaviidae",
    "Red-throated diver",
    "Gavia stellata",
    "Black-throated diver",
    "Gavia arctica",
    "Great northern diver",
    "Gavia immer",
    "Podicipedidae",
    "Little grebe",
    "Tachybaptus ruficollis",
    "Great-crested grebe",
    "Podiceps cristatus",
    "Red-necked grebe",
    "Podiceps grisegena",
    "Slavonian grebe",
    "Podiceps auritus",
    "Black-necked grebe",
    "Podiceps nigricollis",
    "Procellariidae",
    "Fulmar",
    "Fulmarus glacialis",
    "Manx shearwater",
    "Puffinus puffinus",
    "Hydrobatidae",
    "Storm petrel",
    "Hydrobates pelagicus",
    "Leach’s petrel",
    "Oceanodroma leucorhoa",
    "Pelecanoididea",
    "Common diving-petrel",
    "Pelecanoides urinatrix",
    "Pelecanidae",
    "Dalmatian pelican",
    "Pelecanus crispus",
    "Sulidae",
    "Gannet",
    "Morus bassanus",
    "Phalacrocoracidae",
    "Cormorant ",
    "Phalacrocorax carbo",
    "Shag",
    "Phalacrocorax aristotelis",
    "Ardeidae",
    "Little bittern",
    "Ixobrychus minutus",
    "Bittern",
    "Botaurus stellaris",
    "Grey heron",
    "Ardea cinerea",
    "Anatidae",
    "Mute swan ",
    "Cygnus olor",
    "Bewick’s swan",
    "Cygnus columbianus",
    "Whooper swan",
    "Cygnus cygnus",
    "Bean goose",
    "Anser fabalis",
    "Pink-footed goose",
    "Anser brachyrhynchus",
    "White-fronted goose",
    "Anser albifrons",
    "Greylag",
    "Anser anser",
    "Canada goose",
    "Branta canadensis",
    "Barnacle goose",
    "Branta leucopsis",
    "Brent goose",
    "Branta bernicla",
    "Egyptian goose",
    "Alopochen aegyptiacus",
    "Shelduck",
    "Tadorna tadorna",
    "Mandarin",
    "Aix galericulata",
    "Wood duck",
    "Aix sponsa",
    "Wigeon",
    "Anas penelope",
    "Gadwall",
    "Anas strepera",
    "Teal",
    "Anas crecca",
    "Mallard",
    "Anas platyrhynchos",
    "Pintail",
    "Anas acuta",
    "Garganey",
    "Anas querquedula",
    "Shoveler",
    "Anas clypeata",
    "Red-crested pochard",
    "Netta rufina",
    "Pochard",
    "Aythya ferina",
    "Tufted duck",
    "Aythya fuligula",
    "Greater scaup",
    "Aythya marila",
    "Eider",
    "Somateria mollissima",
    "Long-tailed duck",
    "Clangula hyemalis",
    "Common scoter",
    "Melanitta nigra",
    "Velvet scoter",
    "Melanitta fusca",
    "Goldeneye",
    "Bucephala clangula",
    "Smew",
    "Mergellus albellus",
    "Red-breasted merganser",
    "Mergus serrator",
    "Goosander",
    "Mergus merganser",
    "Ruddy duck",
    "Oxyura jamaicensis",
    "White-headed duck",
    "Oxyura leucocephala",
    "Pandionidae",
    "Osprey",
    "Pandion haliaetus",
    "Accipitridae",
    "Honey buzzard",
    "Pernis apivorus",
    "Red kite",
    "Milvus milvus",
    "White-tailed sea-eagle",
    "Haliaeetus albicilla",
    "Marsh harrier",
    "Circus aeruginosus",
    "Hen harrier",
    "Circus cyaneus",
    "Montagu’s harrier",
    "Circus pygargus",
    "Goshawk",
    "Accipiter gentilis",
    "Sparrowhawk",
    "Accipiter nisus",
    "Buzzard",
    "Buteo buteo",
    "Rough-legged buzzard",
    "Buteo lagopus",
    "Golden eagle",
    "Aquila chrysaetos",
    "Falconidae",
    "Kestrel",
    "Falco tinnunculus",
    "American kestrel",
    "Falco sparverius",
    "Merlin",
    "Falco columbarius",
    "Hobby",
    "Falco subbuteo",
    "Peregrine",
    "Falco peregrinus",
    "Phasianidae",
    "Red grouse",
    "Lagopus lagopus",
    "Ptarmigan",
    "Lagopus mutus",
    "Black grouse",
    "Tetrao tetrix",
    "Capercaillie",
    "Tetrao urogallus",
    "Red-legged partridge",
    "Alectoris rufa",
    "Grey partridge",
    "Perdix perdix",
    "Quail",
    "Coturnix coturnix",
    "Ring-necked pheasant",
    "Phasianus colchicus",
    "Golden pheasant",
    "Chrysolophus pictus",
    "Lady Amherst’s pheasant",
    "Chrysolophus amherstiae",
    "Gruidae",
    "Crane",
    "Grus grus",
    "Rallidae",
    "Water rail",
    "Rallus aquaticus",
    "Spotted crake",
    "Porzana porzana",
    "Baillon’s crake",
    "Porzana pusilla",
    "Corncrake",
    "Crex crex",
    "Moorhen",
    "Gallinula chloropus",
    "Coot",
    "Fulica atra",
    "Otididae",
    "Great bustard",
    "Otis tarda",
    "Haematopodidae",
    "Oystercatcher",
    "Haematopus ostralegus",
    "Recurvirostridae",
    "Black-winged stilt",
    "Himantopus himantopus",
    "Avocet",
    "Recurvirostra avosetta",
    "Burhunidae",
    "Stone-curlew",
    "Burhinus oedicnemus",
    "Charadriidae",
    "Little ringed plover",
    "Charadrius dubius",
    "Ringed plover",
    "Charadrius hiaticula",
    "Dotterel",
    "Eudromias morinellus",
    "Golden plover",
    "Pluvialis apricaria",
    "Grey plover",
    "Pluvialis squatarola",
    "Lapwing",
    "Vanellus vanellus",
    "Scolopacidae",
    "Knot",
    "Calidris canutus",
    "Sanderling",
    "Calidris alba",
    "Temminck’s stint",
    "Calidris temminckii",
    "Purple sandpiper",
    "Calidris maritima",
    "Dunlin",
    "Calidris alpina",
    "Ruff",
    "Philomachus pugnax",
    "Jack snipe",
    "Lymnocryptes minimus",
    "Snipe",
    "Gallinago gallinago",
    "Woodcock",
    "Scolopax rusticola",
    "Black-tailed godwit",
    "Limosa limosa",
    "Bar-tailed godwit",
    "Limosa lapponica",
    "Whimbrel",
    "Numenius phaeopus",
    "Curlew",
    "Numenius arquata",
    "Spotted redshank",
    "Tringa erythropus",
    "Redshank",
    "Tringa totanus",
    "Greenshank",
    "Tringa nebularia",
    "Green sandpiper",
    "Tringa ochropus",
    "Wood sandpiper",
    "Tringa glareola",
    "Common sandpiper",
    "Tringa hypoleucos",
    "Spotted sandpiper",
    "Tringa macularia",
    "Turnstone",
    "Arenaria interpres",
    "Red-necked phalarope",
    "Phalaropus lobatus",
    "Stercorariidae",
    "Arctic skua",
    "Stercorarius parasiticus",
    "Great skua",
    "Catharacta skua",
    "Laridae",
    "Little gull",
    "Larus minutus",
    "Mediterranean gull",
    "Larus melanocephalus",
    "Family",
    "Common name",
    "Scientific name",
    "Black-headed gull",
    "Larus ridibundus",
    "Common gull",
    "Larus canus",
    "Lesser black-backed gull",
    "Larus fuscus",
    "Herring gull",
    "Larus argentatus",
    "Great black-backed gull",
    "Larus marinus",
    "Kittiwake",
    "Rissa tridactyla",
    "Sandwich tern",
    "Sterna sandvicensis",
    "Roseate tern",
    "Sterna dougallii",
    "Common tern",
    "Sterna hirundo",
    "Arctic tern",
    "Sterna paradisaea",
    "Little tern",
    "Sterna albifrons",
    "Black tern",
    "Chlidonias niger",
    "Alcidae",
    "Great auk",
    "Pinguinus impennis",
    "Guillemot",
    "Uria aalge",
    "Razorbill",
    "Alca torda",
    "Black guillemot",
    "Cepphus grylle",
    "Puffin",
    "Fratercula arctica",
    "Columbidae",
    "Stock dove",
    "Columba oenas",
    "Feral pigeon/rock dove",
    "Columba livia",
    "Woodpigeon",
    "Columba palumbus",
    "Collared dove",
    "Streptopelia decaocto",
    "Turtle dove",
    "Streptopelia turtur",
    "Psittacidae",
    "Rose-ringed parakeet",
    "Psittacula krameri",
    "Cuculidae",
    "Cuckoo",
    "Cuculus canorus",
    "Tytonidae",
    "Barn owl",
    "Tyto alba",
    "Strigidae",
    "Snowy owl",
    "Nyctea scandiaca",
    "Little owl",
    "Athene noctua",
    "Tawny owl",
    "Strix aluco",
    "Long-eared owl",
    "Asio otus",
    "Short-eared owl",
    "Asio flammeus",
    "Caprimulgidae",
    "Common poorwill",
    "Phalaenoptilus nuttallii",
    "Nightjar",
    "Caprimulgus europaeus",
    "Apodidae",
    "Swift",
    "Apus apus",
    "Trochilidae",
    "Anna’s hummingbird",
    "Calypte anna",
    "Ruby-throated hummingbird",
    "Archilochus colubris",
    "Alcedinidae",
    "Kingfisher",
    "Alcedo atthis",
    "Upupidae",
    "Hoopoe",
    "Upupa epops",
    "Picidae",
    "Wryneck",
    "Jynx torquilla",
    "Green woodpecker",
    "Picus viridis",
    "Great spotted woodpecker",
    "Dendrocopos major",
    "Lesser spotted woodpecker",
    "Dendrocopos minor",
    "Alaudidae",
    "Woodlark",
    "Lullula arborea",
    "arvensis",
    "Eremophila alpestris",
    "riparia",
    "rustica",
    "Delichon urbica",
    "Tree pipit",
    "Anthus trivialis",
    "Anthus pratensis",
];

export default latinNames;